/*
 *    Copyright 2013 Information Control Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.simpliccity.styleguide.plugin.report;

import java.io.File;
import java.util.List;

import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.simpliccity.styleguide.maven.util.StyleGuideException;

/**
 * Renders a StyleGuide report based on content generated by the <code>collate</code> goal.
 * 
 * @author Kevin Fox
 *
 */
@Mojo(name="report", defaultPhase=LifecyclePhase.SITE)
public class PrebuiltStyleGuideReport extends AbstractStyleGuideReport 
{
	@Override
	protected List<String> getSourcePaths() 
	{
		// Empty implementation, as source paths are not used by this report
		return null;
	}

	@Override
	protected File generateContent() throws StyleGuideException
	{
		// Implementation that returns a pre-built file, likely created by the collate goal
		return getReportFile();
	}
}
